import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import GlobalState from '@/context'
import Navbar from '@/components/Navbar'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import LoadingPage from '@/components/Loading'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
         <ToastContainer/>
        <GlobalState>
         <Navbar/>
         <LoadingPage/>
         <main className='flex flex-col mt-[65px]'>{children}</main>
        </GlobalState>
        </body>
    </html>
  )
}
